### ISSUE TITLE
How to capture from the previously found non-capturing group using Super Expressive?

### ISSUE THREAD

**Issue by cksachdev** [francisrstokes/super-expressive#52]
Test string:
```
if ( typeof(NewContent) != 'undefined' ) {NewContent('005056B6F1202A0A45AC13010029C376','2',{'title':'Audio Transcript','y':0,'x':0,'height':450,'width':400,'modal':false,'fixedcenter':false});}">Audio Transcript</a></p>
```

Trying to capture the value of NewContent function in single quotes. There can be one or more instances, thus need to use named capture groups.

SuperExpressive methods used:
```
SuperExpressive()
    .optional.group
        .string("{NewContent('")
    .end()
    .capture
        .word
    .end()
    .optional.group
        .string("'")
    .end()
    .toRegex()
```

Current output:
```
/(?:\{NewContent\(')?(\w)(?:')?/
```

Expected output:
```
(?:\{NewContent\(')(\w+)(?:')
```

Could you please suggest which method I should use to start the capture from the previously found non-capturing group?

**Comment by francisrstokes** [comment]
I don't 100% understand what you mean by "start the capture from the previously found non-capturing group", but to get to your expected regex you would write this:

```javascript
SuperExpressive()
    .group
        .string("{NewContent('")
    .end()
    .capture
        .oneOrMore.word
    .end()
    .group
        .string("'")
    .end()
    .toRegex()
```

You can use `.namedCapture('newContentValue')` instead of `.capture` if you want to be able to reference the result by name, but it would capture the value either way.
