### ISSUE TITLE
Is there some reason why all methods with no arguments are properties, but .end() is an exclusion?

### ISSUE THREAD

**Issue by stanislav-tsaplev** [francisrstokes/super-expressive#60]

**Comment by francisrstokes** [comment]
Yes this was a conscious design choice. The idea was that all other properties requiring no args are the beginning of a *context* inside the SuperExpressive object, but `.end()` is distinct because it applies to all of them. I found that it helped me to visually parse the end of a context quickly in the flat fluent API this way. Somewhat arbitrary, but there you go.
